import json
import sys

import pytest

import session_view as sv


def test_load_events_skips_malformed_lines(tmp_path, capsys):
    path = tmp_path / "events.jsonl"
    path.write_text(
        '{"type":"user.message","data":{"content":"ok"}}\n'
        'not json\n'
        '{"type":"assistant.message","data":{"content":"done"}}\n',
        encoding="utf-8",
    )

    events = sv.load_events(str(path))

    assert len(events) == 2
    assert events[0]["type"] == "user.message"
    assert "Warning: skipping malformed line 2" in capsys.readouterr().err


def test_load_events_can_skip_malformed_lines_quietly(tmp_path, capsys):
    path = tmp_path / "events.jsonl"
    path.write_text("not json\n", encoding="utf-8")

    assert sv.load_events(str(path), warn_malformed=False) == []
    assert capsys.readouterr().err == ""


def test_build_overview_html_embeds_search_payload_and_filters_internal_story_sessions():
    html = sv.build_overview_html(
        [
            {
                "id": "rich-session",
                "events_html": "/tmp/rich/events.html",
                "start_time": "2026-05-16T10:00:00Z",
                "cwd": "/tmp/example/project",
                "first_prompt": "Render the session nicely",
                "search_text": "reasoning text and assistant reply",
                "model": "gpt-5.4",
                "user_prompt_count": 1,
                "has_story": True,
                "total_nano_aiu": 2_000_000_000,
                "model_metrics": {},
                "summary": "Merged summary",
            },
            {
                "id": "internal-story",
                "events_html": "/tmp/internal/events.html",
                "start_time": "2026-05-16T10:00:00Z",
                "cwd": "/tmp/example/project",
                "first_prompt": "Read the Copilot session below and write a text in English",
                "search_text": "internal story prompt",
                "model": "gpt-5.4",
                "user_prompt_count": 1,
                "has_story": False,
                "total_nano_aiu": 0,
                "model_metrics": {},
                "summary": "",
            },
        ]
    )

    assert "reasoning text and assistant reply" in html
    assert "Render the session nicely" in html
    assert '"activity": "1"' in html
    assert '"activity_total": 1' in html
    assert 'title="user prompts">Prompts' in html
    assert '"ai_credits": 2.0' in html
    assert "Read the Copilot session below" not in html
    assert "url.searchParams.set('q', value);" in html
    assert "foo NOT bar" in html
    assert 'id="search-highlight"' in html
    assert ".search-operator" in html
    assert ".search-highlight,\n.search-bar" in html
    assert "font-family: inherit;" in html
    assert "line-height: normal;" in html
    assert 'id="btn-expand"' not in html
    assert 'id="btn-collapse"' not in html
    assert "toggleGroup" not in html


def test_build_overview_html_omits_legacy_search_duplicate_for_scoped_sessions():
    html = sv.build_overview_html(
        [{
            "id": "scoped-session",
            "events_html": "/tmp/scoped/events.html",
            "start_time": "2026-05-16T10:00:00Z",
            "cwd": "/tmp/example/project",
            "first_prompt": "Scoped prompt",
            "search_text": "legacy duplicate payload",
            "search_fields": {
                field: "searchable content" if field == "prompts" else ""
                for field in sv.SEARCH_FIELD_ORDER
            },
            "model": "gpt-5.4",
            "user_prompt_count": 1,
            "has_story": False,
            "total_nano_aiu": 0,
            "model_metrics": {},
            "summary": "",
        }]
    )

    assert '"search": "legacy duplicate payload"' not in html
    assert '"search_fields"' in html


def test_build_overview_html_matches_full_and_displayed_directories_like_models():
    html = sv.build_overview_html(
        [
            {
                "id": "directory-session",
                "events_html": "/tmp/directory/events.html",
                "start_time": "2026-05-16T10:00:00Z",
                "cwd": "/tmp/example/project",
                "first_prompt": "Find the directory session",
                "search_text": "",
                "model": "gpt-5.4",
                "user_prompt_count": 1,
                "has_story": False,
                "total_nano_aiu": 0,
                "model_metrics": {},
                "summary": "",
            },
        ]
    )

    assert '"cwd": "/tmp/example/project"' in html
    assert '"cwd_display": "example/project"' in html
    assert "function matchesQuery(item, q)" not in html
    assert "item.cwd_display" in html
    assert "item.model" in html
    assert "makeDirectorySnippet(item, positiveQuery, snippetSize)" in html


def test_build_overview_html_renders_scoped_search_controls(rich_session_dir):
    (rich_session_dir / "story.txt").write_text("Story generated by test", encoding="utf-8")
    session = sv.read_session(rich_session_dir)
    session["summary"] = "Saved summary"

    html = sv.build_overview_html([session])

    assert 'id="search-fields"' in html
    assert '<legend>Match in</legend>' in html
    assert 'id="btn-select-all"' in html
    assert 'id="btn-select-none"' in html
    assert 'id="search-status"' in html
    assert 'aria-live="polite"' in html
    toolbar_start = html.index('<div class="toolbar">')
    fieldset_start = html.index('<fieldset class="search-fields"', toolbar_start)
    toolbar_end = html.index('\n      </div>\n      <div class="search-status"', fieldset_start)
    status_start = html.index('<div class="search-status"', toolbar_start)
    assert toolbar_start < fieldset_start < toolbar_end < status_start
    for field in sv.SEARCH_FIELD_ORDER:
        assert f'data-search-field="{field}" checked' in html
    assert '"search_fields"' in html
    assert '"Story generated by test"' in html


def test_build_overview_html_escapes_script_terminators_in_search_data():
    dangerous = "</script><script>break the page</script>"
    html = sv.build_overview_html(
        [{
            "id": "script-content",
            "events_html": "/tmp/script-content/events.html",
            "start_time": "2026-05-16T10:00:00Z",
            "cwd": "/tmp/example/project",
            "first_prompt": dangerous,
            "search_text": dangerous,
            "search_fields": {
                field: dangerous if field == "replies" else ""
                for field in sv.SEARCH_FIELD_ORDER
            },
            "model": "gpt-5.4",
            "user_prompt_count": 1,
            "has_story": False,
            "total_nano_aiu": 0,
            "model_metrics": {},
            "summary": "",
        }]
    )

    assert html.count("</script>") == 1
    assert "\\u003c/script\\u003e" in html


def test_main_resolves_bare_session_id_and_writes_html(rich_session_dir, monkeypatch):
    monkeypatch.setattr(sys, "argv", ["session_view.py", "rich-session"])

    sv.main()

    html = (rich_session_dir / "events.html").read_text(encoding="utf-8")
    assert "Render the session nicely" in html
    assert "Rendering session view" in html
    assert "The explore agent inspected the rendering path." in html
    assert sv._overview_output_path().exists()


@pytest.mark.parametrize(
    ("argv", "expected"),
    [
        (["-l", "Swedish", "INPUT"], "-l/--language"),
        (["--force", "INPUT"], "-f/--force"),
        (["--story"], "--story is not valid in batch mode."),
    ],
)
def test_main_rejects_invalid_flag_combinations(rich_session_dir, monkeypatch, capsys, argv, expected):
    resolved = [
        str(rich_session_dir / "events.jsonl") if value == "INPUT" else value
        for value in argv
    ]
    monkeypatch.setattr(sys, "argv", ["session_view.py", *resolved])

    with pytest.raises(SystemExit) as exc:
        sv.main()

    assert exc.value.code == 1
    assert expected in capsys.readouterr().err


def test_main_batch_mode_skips_up_to_date_outputs(write_session_fixture, monkeypatch, capsys):
    session_dir = write_session_fixture("rich-session.jsonl", session_id="rich-session")
    input_path = session_dir / "events.jsonl"
    output_path = session_dir / "events.html"
    output_path.write_text("already rendered", encoding="utf-8")

    input_mtime = input_path.stat().st_mtime
    output_mtime = input_mtime + 100
    monkeypatch.setattr(sv, "_effective_source_mtime", lambda: 0)
    monkeypatch.setattr(sys, "argv", ["session_view.py"])

    output_path.touch()
    import os

    os.utime(output_path, (output_mtime, output_mtime))

    sv.main()

    captured = capsys.readouterr()
    assert "100% [0s] - Up to date:" in captured.out
    assert "Done: 0 written, 1 skipped." in captured.out
    assert not sv._overview_output_path().exists()


def test_main_batch_mode_reports_progress_for_skipped_and_written_files(
    write_session_fixture,
    monkeypatch,
    capsys,
):
    skipped_dir = write_session_fixture("rich-session.jsonl", session_id="a-skipped")
    written_dir = write_session_fixture("rich-session.jsonl", session_id="b-written")
    skipped_input = skipped_dir / "events.jsonl"
    skipped_output = skipped_dir / "events.html"
    skipped_output.write_text("already rendered", encoding="utf-8")

    import os

    os.utime(skipped_output, (skipped_input.stat().st_mtime + 100,) * 2)
    monkeypatch.setattr(sv, "_effective_source_mtime", lambda: 0)
    clock = iter((0.0, 30.0, 120.0))
    monkeypatch.setattr(sv.time, "monotonic", lambda: next(clock))
    monkeypatch.setattr(sys, "argv", ["session_view.py"])

    sv.main()

    captured = capsys.readouterr()
    assert " 50% [30s] - Up to date:" in captured.out
    assert "100% [0s] ✓ " in captured.out
    assert "Done: 1 written, 1 skipped." in captured.out
    assert (written_dir / "events.html").exists()


@pytest.mark.parametrize(
    ("seconds", "expected"),
    [
        (0, "0s"),
        (9, "9s"),
        (69, "1m9s"),
        (3663, "1h1m3s"),
    ],
)
def test_format_duration(seconds, expected):
    assert sv._format_duration(seconds) == expected


def test_process_file_skips_empty_input(tmp_path, capsys):
    input_path = tmp_path / "events.jsonl"
    input_path.write_text("", encoding="utf-8")

    assert sv.process_file(str(input_path), str(tmp_path / "events.html")) is None

    assert "⚠ No events found, skipping:" in capsys.readouterr().err


def test_overview_refreshes_when_story_is_newer(write_session_fixture, monkeypatch):
    session_dir = write_session_fixture("rich-session.jsonl", session_id="rich-session")
    story_path = session_dir / "story.txt"
    story_path.write_text("new story", encoding="utf-8")
    overview_path = sv._overview_output_path()
    overview_path.write_text("old overview", encoding="utf-8")

    monkeypatch.setattr(sv, "_effective_source_mtime", lambda: 0)
    import os

    os.utime(overview_path, (100, 100))
    os.utime(story_path, (200, 200))
    assert sv._overview_needs_refresh() is True

    os.utime(story_path, (50, 50))
    assert sv._overview_needs_refresh() is False


def test_main_batch_mode_generates_overview_and_filters_internal_story_sessions(
    write_session_fixture,
    monkeypatch,
):
    rich_session_dir = write_session_fixture("rich-session.jsonl", session_id="rich-session")
    write_session_fixture("internal-story-session.jsonl", session_id="internal-story-session")
    monkeypatch.setattr(sys, "argv", ["session_view.py"])

    sv.main()

    assert (rich_session_dir / "events.html").exists()
    overview_html = sv._overview_output_path().read_text(encoding="utf-8")
    assert "Render the session nicely" in overview_html
    assert "Read the Copilot session below" not in overview_html


def test_generate_overview_merges_json_and_db_summaries(
    rich_session_dir,
    isolated_home,
    create_session_store_db,
):
    (rich_session_dir / "events.html").write_text("<html></html>", encoding="utf-8")
    summaries_path = isolated_home / ".copilot" / "session-summaries.json"
    summaries_path.write_text(json.dumps({"rich-session": "Saved summary"}), encoding="utf-8")
    create_session_store_db({"rich-session": "DB summary", "other-session": "Extra summary"})

    sv.generate_overview()

    overview_html = sv._overview_output_path().read_text(encoding="utf-8")
    persisted = json.loads(summaries_path.read_text(encoding="utf-8"))

    assert "DB summary" in overview_html
    assert "Saved summary" not in overview_html
    assert persisted["rich-session"] == "DB summary"
    assert persisted["other-session"] == "Extra summary"
