from subprocess import CompletedProcess, TimeoutExpired

import session_view as sv


def test_generate_story_uses_cached_story_without_running_copilot(rich_session_dir, monkeypatch):
    jsonl_path = rich_session_dir / "events.jsonl"
    cache_path = rich_session_dir / "story.txt"
    cache_path.write_text("cached story", encoding="utf-8")
    called = {"value": False}

    def fake_run(_cmd):
        called["value"] = True
        raise AssertionError("story subprocess should not run when cache exists")

    monkeypatch.setattr(sv, "_run_story_command", fake_run)

    assert sv.generate_story(str(jsonl_path)) == "cached story"
    assert called["value"] is False


def test_generate_story_writes_cache_from_subprocess_output(rich_session_dir, monkeypatch):
    jsonl_path = rich_session_dir / "events.jsonl"
    captured = {}

    def fake_run(cmd):
        captured["cmd"] = cmd
        return CompletedProcess(
            cmd,
            0,
            stdout="preface\nStory generated by claude-haiku-4.5\nChapter 1\n",
            stderr="",
        )

    monkeypatch.setattr(sv, "_current_username", lambda: "jonas")
    monkeypatch.setattr(sv, "_run_story_command", fake_run)

    story = sv.generate_story(str(jsonl_path), force=True, language="Swedish")
    prompt = captured["cmd"][-1]

    assert story == "Story generated by claude-haiku-4.5\nChapter 1"
    assert (rich_session_dir / "story.txt").read_text(encoding="utf-8") == story
    assert (rich_session_dir / "events.txt").exists()
    assert "text in the Swedish language" in prompt
    assert "plain text in your response" in prompt
    assert "do not write it to any file and do not use any tools" in prompt


def test_generate_story_falls_back_to_environment_username(rich_session_dir, monkeypatch):
    jsonl_path = rich_session_dir / "events.jsonl"

    def fake_run(cmd):
        return CompletedProcess(
            cmd,
            0,
            stdout="Story generated by claude-haiku-4.5\nChapter 1\n",
            stderr="",
        )

    monkeypatch.setattr(sv.os, "getlogin", lambda: (_ for _ in ()).throw(OSError("no tty")))
    monkeypatch.setenv("USER", "ci-user")
    monkeypatch.setattr(sv, "_run_story_command", fake_run)

    sv.generate_story(str(jsonl_path), force=True)

    parsed_events = (rich_session_dir / "events.txt").read_text(encoding="utf-8")
    assert "Session with user 'ci-user' and Copilot" in parsed_events


def test_generate_story_returns_none_on_nonzero_exit(rich_session_dir, monkeypatch, capsys):
    jsonl_path = rich_session_dir / "events.jsonl"

    def fake_run(cmd):
        return CompletedProcess(cmd, 1, stdout="", stderr="boom")

    monkeypatch.setattr(sv, "_current_username", lambda: "jonas")
    monkeypatch.setattr(sv, "_run_story_command", fake_run)

    assert sv.generate_story(str(jsonl_path), force=True) is None
    assert not (rich_session_dir / "story.txt").exists()
    assert "failed (exit 1)" in capsys.readouterr().out


def test_generate_story_returns_none_on_timeout(rich_session_dir, monkeypatch, capsys):
    jsonl_path = rich_session_dir / "events.jsonl"

    def fake_run(_cmd):
        raise TimeoutExpired(cmd="copilot", timeout=600)

    monkeypatch.setattr(sv, "_current_username", lambda: "jonas")
    monkeypatch.setattr(sv, "_run_story_command", fake_run)

    assert sv.generate_story(str(jsonl_path), force=True) is None
    assert not (rich_session_dir / "story.txt").exists()
    assert "failed (timeout)" in capsys.readouterr().out
