import session_view as sv


def test_build_overview_tracks_metrics_and_excludes_report_intent_from_tools_used(rich_events):
    overview = sv.build_overview(rich_events)

    assert overview["session_id"] == "rich-session"
    assert overview["copilot_version"] == "1.0.48"
    assert overview["duration_ms"] == 10000
    assert overview["tools_used"] == {"bash": 1}
    assert overview["intents"] == ["Rendering session view"]
    assert overview["lines_added"] == 12
    assert overview["lines_removed"] == 3
    assert overview["total_premium_requests"] == 2


def test_build_turns_reconstructs_reasoning_intent_tool_and_subagent_steps(rich_events):
    turns = sv.build_turns(rich_events)

    assert len(turns) == 1
    assert turns[0]["user_message"]["content"] == "Render the session nicely"
    assert [step["kind"] for step in turns[0]["steps"]] == [
        "reasoning",
        "text",
        "intent",
        "tool",
        "text",
        "subagent",
    ]
    assert turns[0]["steps"][2]["content"] == "Rendering session view"
    assert turns[0]["steps"][3]["name"] == "bash"
    assert turns[0]["steps"][3]["result"]["content"].startswith("diff --git")
    assert turns[0]["steps"][5]["name"] == "Explore Agent"
    assert "Session rendering path" in turns[0]["steps"][5]["result"]["content"]


def test_read_session_collects_search_text_and_intent_count(rich_session_dir):
    (rich_session_dir / "story.txt").write_text("Story generated by test\n\nChapter 1", encoding="utf-8")

    info = sv.read_session(rich_session_dir)

    assert info["has_story"] is True
    assert info["model"] == "gpt-5.4"
    assert info["user_prompt_count"] == 1
    assert info["intent_count"] == 1
    assert info["first_prompt"] == "Render the session nicely"
    assert "**Plan**: inspect rendered output." in info["search_text"]
    assert "Rendering session view" in info["search_text"]


def test_process_file_renders_story_tab_a11y_and_query_hooks(rich_session_dir, tmp_path):
    (rich_session_dir / "story.txt").write_text(
        "Story generated by test\n\nFirst chapter\n\nSecond chapter",
        encoding="utf-8",
    )
    output_path = tmp_path / "events.html"

    sv.process_file(
        str(rich_session_dir / "events.jsonl"),
        str(output_path),
        a11y=True,
        story=False,
    )

    html = output_path.read_text(encoding="utf-8")

    assert "📖 Story" in html
    assert '<p class="story-p">Story generated by test</p>' in html
    assert "First chapter" in html
    assert sv.CSS_A11Y.strip() in html
    assert 'class="back-link"' in html
    assert "url.searchParams.set('q', query);" in html


def test_render_args_and_results_handle_sql_apply_patch_line_numbers_and_diff():
    sql_html = sv.render_args(
        {"description": "Query sessions", "query": "SELECT 'x' FROM SESSIONS"},
        "sql",
    )
    patch_html = sv.render_args(
        "*** Begin Patch\n*** Add File: demo.txt\n+hello\n*** End Patch\n",
        "apply_patch",
    )
    numbered_html = sv.render_tool_result({"content": "1. alpha\n2. beta\n"}, "view")
    diff_html = sv.render_tool_result(
        {"content": "diff --git a/file.txt b/file.txt\n--- a/file.txt\n+++ b/file.txt\n@@ -1 +1 @@\n-old\n+new\n"},
        "bash",
    )

    assert "sql-block" in sql_html
    assert "sql-kw" in sql_html
    assert 'class="diff-meta"' in patch_html
    assert 'class="line-num"' in numbered_html
    assert 'class="diff-add"' in diff_html
    assert 'class="diff-del"' in diff_html


def test_markdown_to_html_renders_lists_tables_and_inline_markup():
    html = sv.markdown_to_html(
        "**Bold** and `code`\n\n"
        "1. first\n"
        "2. second\n\n"
        "| Name | Value |\n"
        "| --- | --- |\n"
        "| foo | bar |\n"
    )

    assert "<strong>Bold</strong>" in html
    assert '<code class="md-code">code</code>' in html
    assert '<ol class="md-ol">' in html
    assert "<table" in html
